//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeadmanSwitchLauncher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeadmanSwitchLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This launcher is useless till you go through the setup!.
        /// </summary>
        internal static string dbdBuildPromptCancel {
            get {
                return ResourceManager.GetString("dbdBuildPromptCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Canceled.
        /// </summary>
        internal static string dbdBuildPromptCancelTitle {
            get {
                return ResourceManager.GetString("dbdBuildPromptCancelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have the Live or PTB currently installed?.
        /// </summary>
        internal static string dbdBuildPromptLabel {
            get {
                return ResourceManager.GetString("dbdBuildPromptLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live.
        /// </summary>
        internal static string dbdBuildPromptLive {
            get {
                return ResourceManager.GetString("dbdBuildPromptLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PTB.
        /// </summary>
        internal static string dbdBuildPromptPTB {
            get {
                return ResourceManager.GetString("dbdBuildPromptPTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live or PTB.
        /// </summary>
        internal static string dbdBuildPromptTitle {
            get {
                return ResourceManager.GetString("dbdBuildPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Dead By Daylight -&gt; Properties -&gt; Updates and set Automatic Updates to &quot;Only update this game when I launch it&quot;.
        /// </summary>
        internal static string dbdDisableAutoUpdate {
            get {
                return ResourceManager.GetString("dbdDisableAutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember to disable automatic updates for DBD..
        /// </summary>
        internal static string dbdDisableAutoUpdateTitle {
            get {
                return ResourceManager.GetString("dbdDisableAutoUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How&apos;d you end up here?.
        /// </summary>
        internal static string dbdInstallHow {
            get {
                return ResourceManager.GetString("dbdInstallHow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now please install the Live build and hit OK when it&apos;s done..
        /// </summary>
        internal static string dbdInstallLive {
            get {
                return ResourceManager.GetString("dbdInstallLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string dbdInstallPromptButton {
            get {
                return ResourceManager.GetString("dbdInstallPromptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string dbdInstallPromptFinished {
            get {
                return ResourceManager.GetString("dbdInstallPromptFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a valid DBD install folder.
        /// </summary>
        internal static string dbdInstallPromptInvalid {
            get {
                return ResourceManager.GetString("dbdInstallPromptInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DBD Install Path.
        /// </summary>
        internal static string dbdInstallPromptInvalidTitle {
            get {
                return ResourceManager.GetString("dbdInstallPromptInvalidTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your DBD install folder.
        /// </summary>
        internal static string dbdInstallPromptLabel {
            get {
                return ResourceManager.GetString("dbdInstallPromptLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Dead by Daylight Install Path.
        /// </summary>
        internal static string dbdInstallPromptTitle {
            get {
                return ResourceManager.GetString("dbdInstallPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now please install the PTB build and hit OK when it&apos;s done..
        /// </summary>
        internal static string dbdInstallPTB {
            get {
                return ResourceManager.GetString("dbdInstallPTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live.
        /// </summary>
        internal static string dbdLauncherRadioLive {
            get {
                return ResourceManager.GetString("dbdLauncherRadioLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PTB.
        /// </summary>
        internal static string dbdLauncherRadioPTB {
            get {
                return ResourceManager.GetString("dbdLauncherRadioPTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string dbdLauncherSettings {
            get {
                return ResourceManager.GetString("dbdLauncherSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Game.
        /// </summary>
        internal static string dbdLauncherStart {
            get {
                return ResourceManager.GetString("dbdLauncherStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadman Switch Launcher.
        /// </summary>
        internal static string dbdLauncherTitle {
            get {
                return ResourceManager.GetString("dbdLauncherTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The launcher took too long to swap builds. You may want to reinstall DBD and clear settings to setup the launcher again..
        /// </summary>
        internal static string dbdLaunchTimeout {
            get {
                return ResourceManager.GetString("dbdLaunchTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher Timedout.
        /// </summary>
        internal static string dbdLaunchTimeoutTitle {
            get {
                return ResourceManager.GetString("dbdLaunchTimeoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string dbdSettingsCancel {
            get {
                return ResourceManager.GetString("dbdSettingsCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear settings and close launcher.
        /// </summary>
        internal static string dbdSettingsClear {
            get {
                return ResourceManager.GetString("dbdSettingsClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string dbdSettingsClearButton {
            get {
                return ResourceManager.GetString("dbdSettingsClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your settings have been cleared and build folders cleaned out. You may want to verify DBD&apos;s integrity on Steam before you start the game or the launcher again.
        /// </summary>
        internal static string dbdSettingsCleared {
            get {
                return ResourceManager.GetString("dbdSettingsCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Cleared.
        /// </summary>
        internal static string dbdSettingsClearedTitle {
            get {
                return ResourceManager.GetString("dbdSettingsClearedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep launcher open while game is running..
        /// </summary>
        internal static string dbdSettingsKeepLauncherOpen {
            get {
                return ResourceManager.GetString("dbdSettingsKeepLauncherOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string dbdSettingsOk {
            get {
                return ResourceManager.GetString("dbdSettingsOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear your settings?.
        /// </summary>
        internal static string dbdSettingsSure {
            get {
                return ResourceManager.GetString("dbdSettingsSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Settings.
        /// </summary>
        internal static string dbdSettingsSureTitle {
            get {
                return ResourceManager.GetString("dbdSettingsSureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string dbdSettingsTitle {
            get {
                return ResourceManager.GetString("dbdSettingsTitle", resourceCulture);
            }
        }
    }
}
