//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeadmanSwitchLauncher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeadmanSwitchLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string dbdInstallPromptButton {
            get {
                return ResourceManager.GetString("dbdInstallPromptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string dbdInstallPromptFinished {
            get {
                return ResourceManager.GetString("dbdInstallPromptFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a valid DBD install folder.
        /// </summary>
        internal static string dbdInstallPromptInvalid {
            get {
                return ResourceManager.GetString("dbdInstallPromptInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DBD Install Path.
        /// </summary>
        internal static string dbdInstallPromptInvalidTitle {
            get {
                return ResourceManager.GetString("dbdInstallPromptInvalidTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your DBD install folder.
        /// </summary>
        internal static string dbdInstallPromptLabel {
            get {
                return ResourceManager.GetString("dbdInstallPromptLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Dead by Daylight Install Path.
        /// </summary>
        internal static string dbdInstallPromptTitle {
            get {
                return ResourceManager.GetString("dbdInstallPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live.
        /// </summary>
        internal static string dbdLauncherRadioLive {
            get {
                return ResourceManager.GetString("dbdLauncherRadioLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PTB.
        /// </summary>
        internal static string dbdLauncherRadioPTB {
            get {
                return ResourceManager.GetString("dbdLauncherRadioPTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string dbdLauncherSettings {
            get {
                return ResourceManager.GetString("dbdLauncherSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Game.
        /// </summary>
        internal static string dbdLauncherStart {
            get {
                return ResourceManager.GetString("dbdLauncherStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadman Switch Launcher.
        /// </summary>
        internal static string dbdLauncherTitle {
            get {
                return ResourceManager.GetString("dbdLauncherTitle", resourceCulture);
            }
        }
    }
}
